spring.application.name=starter-demo

# MySQL Database Connection, put your MySQL Database config here
spring.datasource.url=jdbc:mysql://localhost:3306/vdo_playtestreservation
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# Server
server.port=8080
